# The winner of the whole tournament is the player with the highest score. Your total score is the sum of your scores for each round. The score for a single round is the score for the shape you selected (1 for Rock, 2 for Paper, and 3 for Scissors) plus the score for the outcome of the round (0 if you lost, 3 if the round was a draw, and 6 if you won).

+´1+(1⊸⊑+3×3|1+-˜´)˘>{"AX"-˜0‿2⊏𝕩}¨•FLines "02.in"
+´((1+3|1-˜+´)+(3×1⊸⊑))˘>{"AX"-˜0‿2⊏𝕩}¨•FLines "02.in"
